name: Olympia
description: Ramblings by Hassaan Ali Wattoo
meta_description: "Ramblings by Hassaan Ali Wattoo"
markdown: redcarpet
gems: [jekyll-paginate]
highlighter: pygments
logo: false
paginate: 15
baseurl: /blog/
future: true
domain_name: 'http://hassaanaliw.me/blog/'
google_analytics: 'UA-54672427-1'

# Details for the RSS feed generator
url:            'http://hassaanaliw.me/blog/'
author:         'Hassaan Ali Wattoo'
